# Default values for homeautomation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eprabab/home_automation
  tag: 1.0-SNAPSHOT
  imagePullPolicy: Always
  command: [ "echo", "SUCCESS" ]

imagePullSecrets:
- name: dockerhubsecret
